"""
Patient Model
=============

Purpose:
    SQLAlchemy model for patient records.
    Stores demographics, contact info, and medical identifiers.

Module: app/models/patient.py
Phase: 1D (Patient Backend)

References:
    - Database Schema: docs/diagrams/database-schema.md
    - Patient Module: docs/phases/phase1/diagrams/patient-module.md
    - Phase 1D Spec: docs/phases/phase1/Phase1D_PatientBackend.md

Relationships:
    - User (created_by, updated_by) - Audit trail
    - Visit (one-to-many) - Patient visits [Phase 2]

MRN Format:
    CLI-YYYY-NNNNN (e.g., CLI-2026-00001)
    Generated by: app/utils/mrn_generator.py
"""

from sqlalchemy import Column, String, Date, ForeignKey
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship
from datetime import date

from app.models.base import BaseModel


class Patient(BaseModel):
    """
    Patient model representing a registered patient in the EHR system.
    
    Attributes:
        mrn: Medical Record Number (unique, auto-generated)
        first_name, last_name: Patient name
        date_of_birth: Date of birth for age calculation
        gender: male, female, or other
        phone: Primary contact number
        blood_group: Blood type (A+, B-, etc.)
        
    Computed Properties:
        full_name: Concatenated first + last name
        age: Calculated from date_of_birth
    """
    
    __tablename__ = "patients"
    
    # Medical Record Number (unique identifier)
    mrn = Column(
        String(20),
        unique=True,
        nullable=False,
        index=True,
    )
    
    # Personal Information
    first_name = Column(String(100), nullable=False, index=True)
    last_name = Column(String(100), nullable=False, index=True)
    date_of_birth = Column(Date, nullable=False)
    gender = Column(String(10), nullable=False)  # male, female, other
    
    # Contact Information
    phone = Column(String(15), nullable=False, index=True)
    email = Column(String(255), nullable=True)
    
    # Address
    address_line1 = Column(String(255), nullable=True)
    address_line2 = Column(String(255), nullable=True)
    city = Column(String(100), nullable=True)
    state = Column(String(100), nullable=True)
    pincode = Column(String(10), nullable=True)
    
    # National IDs (India specific)
    aadhaar_number = Column(String(12), nullable=True)  # Encrypted in production
    abha_id = Column(String(20), nullable=True)  # Ayushman Bharat Health Account
    
    # Emergency Contact
    emergency_contact_name = Column(String(100), nullable=True)
    emergency_contact_phone = Column(String(15), nullable=True)
    
    # Medical Information
    blood_group = Column(String(5), nullable=True)  # A+, A-, B+, etc.
    
    # Audit fields
    created_by = Column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id"),
        nullable=True
    )
    
    # Relationships (added in later phases)
    # visits = relationship("Visit", back_populates="patient")
    
    # Phase 3C: Diagnoses relationship
    diagnoses = relationship(
        "Diagnosis",
        back_populates="patient",
        cascade="all, delete-orphan"
    )
    
    def __repr__(self):
        return f"<Patient {self.mrn} - {self.first_name} {self.last_name}>"
    
    @property
    def age(self) -> int:
        """Calculate age from date of birth"""
        today = date.today()
        return today.year - self.date_of_birth.year - (
            (today.month, today.day) < 
            (self.date_of_birth.month, self.date_of_birth.day)
        )
    
    @property
    def full_name(self) -> str:
        """Get full name"""
        return f"{self.first_name} {self.last_name}"
