"""
Visit Model
===========

Purpose:
    SQLAlchemy model for patient visits/appointments.
    Tracks patient check-in, status, and consultation details.

Module: app/models/visit.py
Phase: 2A (Visit Models)

References:
    - Database Schema: docs/diagrams/database-schema.md
    - Phase 2A Spec: docs/phases/phase2/Phase2A_VisitModels.md
    - Phase 2 Overview: docs/phases/phase2/Phase2_Overview.md

Relationships:
    - Patient (Many-to-One): The patient being seen
    - User/Doctor (Many-to-One): Assigned doctor
    - User (created_by, updated_by): Audit trail

Visit Number Format:
    VIS-YYYY-NNNNN (e.g., VIS-2026-00042)
    Generated by: app/utils/visit_number_generator.py

Status Flow:
    REGISTERED → WAITING → IN_PROGRESS → COMPLETED
    (Any state can transition to CANCELLED)
"""

from sqlalchemy import Column, String, Date, DateTime, Text, ForeignKey, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import relationship
from datetime import datetime

from app.models.base import BaseModel
from app.models.enums import VisitStatus, VisitType, Priority


class Visit(BaseModel):
    """
    Visit model representing a patient visit/appointment.
    
    Tracks the complete lifecycle of a patient visit from check-in
    to consultation completion or cancellation.
    
    Attributes:
        visit_number: Unique identifier (VIS-YYYY-NNNNN)
        patient: The patient being seen
        assigned_doctor: Doctor assigned to the visit
        visit_date: Date of the visit
        visit_type: Type of visit (consultation, follow-up, etc.)
        status: Current status in the visit lifecycle
        priority: Queue priority (normal, urgent, emergency)
        chief_complaint: Main reason for visit
        
    Computed Properties (in schema):
        patient_name: Full name from patient relationship
        doctor_name: Full name from doctor relationship
        wait_time_minutes: Time since check-in (if waiting)
        consultation_duration: End - start time (if completed)
    """
    
    __tablename__ = "visits"
    
    # =========================================================================
    # Visit Identification
    # =========================================================================
    
    visit_number = Column(
        String(20),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique visit ID: VIS-YYYY-NNNNN"
    )
    
    # =========================================================================
    # Relationships
    # =========================================================================
    
    patient_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="FK to patients table"
    )
    
    assigned_doctor_id = Column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        comment="FK to users table (doctor)"
    )
    
    # =========================================================================
    # Visit Details
    # =========================================================================
    
    visit_date = Column(
        Date,
        nullable=False,
        index=True,
        default=datetime.utcnow().date,
        comment="Date of visit"
    )
    
    visit_type = Column(
        SQLEnum(VisitType, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=VisitType.CONSULTATION,
        comment="Type: consultation, follow_up, emergency, procedure"
    )
    
    status = Column(
        SQLEnum(VisitStatus, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=VisitStatus.REGISTERED,
        index=True,
        comment="Current status in visit lifecycle"
    )
    
    priority = Column(
        SQLEnum(Priority, values_callable=lambda x: [e.value for e in x]),
        nullable=False,
        default=Priority.NORMAL,
        comment="Queue priority: normal, urgent, emergency"
    )
    
    department = Column(
        String(100),
        nullable=True,
        comment="Department (e.g., General Medicine, Cardiology)"
    )
    
    chief_complaint = Column(
        Text,
        nullable=True,
        comment="Main reason/complaint for visit"
    )
    
    # =========================================================================
    # Timestamps
    # =========================================================================
    
    check_in_time = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When patient checked in"
    )
    
    consultation_start_time = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When consultation started"
    )
    
    consultation_end_time = Column(
        DateTime(timezone=True),
        nullable=True,
        comment="When consultation ended"
    )
    
    # =========================================================================
    # Notes & Cancellation
    # =========================================================================
    
    cancellation_reason = Column(
        Text,
        nullable=True,
        comment="Reason if visit was cancelled"
    )
    
    notes = Column(
        Text,
        nullable=True,
        comment="Additional notes"
    )
    
    # =========================================================================
    # Audit Fields
    # =========================================================================
    
    created_by = Column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="User who created this visit"
    )
    
    updated_by = Column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
        comment="User who last updated this visit"
    )
    
    # =========================================================================
    # Relationships (ORM)
    # =========================================================================
    
    patient = relationship(
        "Patient",
        foreign_keys=[patient_id],
        backref="visits",
        lazy="joined"
    )
    
    assigned_doctor = relationship(
        "User",
        foreign_keys=[assigned_doctor_id],
        backref="assigned_visits",
        lazy="joined"
    )
    
    created_by_user = relationship(
        "User",
        foreign_keys=[created_by],
        lazy="select"
    )
    
    updated_by_user = relationship(
        "User",
        foreign_keys=[updated_by],
        lazy="select"
    )
    
    # Phase 3A: Vitals relationship
    vitals = relationship(
        "Vital",
        back_populates="visit",
        cascade="all, delete-orphan"
    )
    
    # Phase 3C: Diagnoses relationship
    diagnoses = relationship(
        "Diagnosis",
        back_populates="visit",
        cascade="all, delete-orphan"
    )
    
    # Phase 3E: Clinical Notes relationship
    clinical_notes = relationship(
        "ClinicalNote",
        back_populates="visit",
        cascade="all, delete-orphan"
    )
    
    def __repr__(self) -> str:
        return f"<Visit {self.visit_number} - {self.status.value}>"
