"""add orders system

Revision ID: 677224297251
Revises: 38e3d565e383
Create Date: 2026-02-05 19:45:47.501284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '677224297251'
down_revision: Union[str, None] = '38e3d565e383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_note_templates_is_active', table_name='note_templates')
    op.drop_index('idx_note_templates_note_type', table_name='note_templates')
    op.drop_table('note_templates')
    op.drop_index('idx_clinical_notes_created_at', table_name='clinical_notes')
    op.drop_index('idx_clinical_notes_created_by', table_name='clinical_notes')
    op.drop_index('idx_clinical_notes_is_deleted', table_name='clinical_notes')
    op.drop_index('idx_clinical_notes_patient_id', table_name='clinical_notes')
    op.drop_index('idx_clinical_notes_visit_id', table_name='clinical_notes')
    op.drop_index('idx_clinical_notes_visit_primary', table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.alter_column('diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_diagnoses_date', table_name='diagnoses')
    op.drop_index('idx_diagnoses_icd10', table_name='diagnoses')
    op.drop_index('idx_diagnoses_patient', table_name='diagnoses')
    op.drop_index('idx_diagnoses_type', table_name='diagnoses')
    op.drop_index('idx_diagnoses_visit', table_name='diagnoses')
    op.create_index(op.f('ix_diagnoses_id'), 'diagnoses', ['id'], unique=True)
    op.create_index(op.f('ix_diagnoses_is_deleted'), 'diagnoses', ['is_deleted'], unique=False)
    op.drop_index('idx_icd10_category', table_name='icd10_codes')
    op.drop_index('idx_icd10_common', table_name='icd10_codes')
    op.drop_index('idx_icd10_search', table_name='icd10_codes', postgresql_using='gin')
    op.drop_index('idx_icd10_usage', table_name='icd10_codes')
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               comment='Setting key (unique identifier)',
               existing_nullable=False)
    op.alter_column('system_settings', 'value',
               existing_type=sa.VARCHAR(length=500),
               comment='Setting value',
               existing_nullable=False)
    op.alter_column('system_settings', 'description',
               existing_type=sa.TEXT(),
               comment='Human-readable description',
               existing_nullable=True)
    op.alter_column('system_settings', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment='Category for grouping (features, display, limits)',
               existing_nullable=True)
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=True)
    op.create_index(op.f('ix_system_settings_is_deleted'), 'system_settings', ['is_deleted'], unique=False)
    op.alter_column('visits', 'visit_number',
               existing_type=sa.VARCHAR(length=20),
               comment='Unique visit ID: VIS-YYYY-NNNNN',
               existing_nullable=False)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.UUID(),
               comment='FK to patients table',
               existing_nullable=False)
    op.alter_column('visits', 'assigned_doctor_id',
               existing_type=sa.UUID(),
               comment='FK to users table (doctor)',
               existing_nullable=True)
    op.alter_column('visits', 'visit_date',
               existing_type=sa.DATE(),
               comment='Date of visit',
               existing_nullable=False)
    op.alter_column('visits', 'visit_type',
               existing_type=postgresql.ENUM('consultation', 'follow_up', 'emergency', 'procedure', name='visittype'),
               comment='Type: consultation, follow_up, emergency, procedure',
               existing_nullable=False,
               existing_server_default=sa.text("'consultation'::visittype"))
    op.alter_column('visits', 'status',
               existing_type=postgresql.ENUM('registered', 'waiting', 'in_progress', 'completed', 'cancelled', name='visitstatus'),
               comment='Current status in visit lifecycle',
               existing_nullable=False,
               existing_server_default=sa.text("'registered'::visitstatus"))
    op.alter_column('visits', 'priority',
               existing_type=postgresql.ENUM('normal', 'urgent', 'emergency', name='priority'),
               comment='Queue priority: normal, urgent, emergency',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::priority"))
    op.alter_column('visits', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment='Department (e.g., General Medicine, Cardiology)',
               existing_nullable=True)
    op.alter_column('visits', 'chief_complaint',
               existing_type=sa.TEXT(),
               comment='Main reason/complaint for visit',
               existing_nullable=True)
    op.alter_column('visits', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When patient checked in',
               existing_nullable=True)
    op.alter_column('visits', 'consultation_start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When consultation started',
               existing_nullable=True)
    op.alter_column('visits', 'consultation_end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When consultation ended',
               existing_nullable=True)
    op.alter_column('visits', 'cancellation_reason',
               existing_type=sa.TEXT(),
               comment='Reason if visit was cancelled',
               existing_nullable=True)
    op.alter_column('visits', 'notes',
               existing_type=sa.TEXT(),
               comment='Additional notes',
               existing_nullable=True)
    op.alter_column('visits', 'created_by',
               existing_type=sa.UUID(),
               comment='User who created this visit',
               existing_nullable=True)
    op.alter_column('visits', 'updated_by',
               existing_type=sa.UUID(),
               comment='User who last updated this visit',
               existing_nullable=True)
    op.drop_index('ix_visits_date_status', table_name='visits')
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=True)
    op.alter_column('vitals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vitals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vitals', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index('idx_vitals_patient', table_name='vitals')
    op.drop_index('idx_vitals_recorded_at', table_name='vitals')
    op.drop_index('idx_vitals_visit', table_name='vitals')
    op.create_index(op.f('ix_vitals_id'), 'vitals', ['id'], unique=True)
    op.create_index(op.f('ix_vitals_is_deleted'), 'vitals', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vitals_is_deleted'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_id'), table_name='vitals')
    op.create_index('idx_vitals_visit', 'vitals', ['visit_id'], unique=False)
    op.create_index('idx_vitals_recorded_at', 'vitals', ['recorded_at'], unique=False)
    op.create_index('idx_vitals_patient', 'vitals', ['patient_id'], unique=False)
    op.alter_column('vitals', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('vitals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vitals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.create_index('ix_visits_date_status', 'visits', ['visit_date', 'status'], unique=False)
    op.alter_column('visits', 'updated_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who last updated this visit',
               existing_nullable=True)
    op.alter_column('visits', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='User who created this visit',
               existing_nullable=True)
    op.alter_column('visits', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Additional notes',
               existing_nullable=True)
    op.alter_column('visits', 'cancellation_reason',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Reason if visit was cancelled',
               existing_nullable=True)
    op.alter_column('visits', 'consultation_end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When consultation ended',
               existing_nullable=True)
    op.alter_column('visits', 'consultation_start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When consultation started',
               existing_nullable=True)
    op.alter_column('visits', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When patient checked in',
               existing_nullable=True)
    op.alter_column('visits', 'chief_complaint',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Main reason/complaint for visit',
               existing_nullable=True)
    op.alter_column('visits', 'department',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Department (e.g., General Medicine, Cardiology)',
               existing_nullable=True)
    op.alter_column('visits', 'priority',
               existing_type=postgresql.ENUM('normal', 'urgent', 'emergency', name='priority'),
               comment=None,
               existing_comment='Queue priority: normal, urgent, emergency',
               existing_nullable=False,
               existing_server_default=sa.text("'normal'::priority"))
    op.alter_column('visits', 'status',
               existing_type=postgresql.ENUM('registered', 'waiting', 'in_progress', 'completed', 'cancelled', name='visitstatus'),
               comment=None,
               existing_comment='Current status in visit lifecycle',
               existing_nullable=False,
               existing_server_default=sa.text("'registered'::visitstatus"))
    op.alter_column('visits', 'visit_type',
               existing_type=postgresql.ENUM('consultation', 'follow_up', 'emergency', 'procedure', name='visittype'),
               comment=None,
               existing_comment='Type: consultation, follow_up, emergency, procedure',
               existing_nullable=False,
               existing_server_default=sa.text("'consultation'::visittype"))
    op.alter_column('visits', 'visit_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Date of visit',
               existing_nullable=False)
    op.alter_column('visits', 'assigned_doctor_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to users table (doctor)',
               existing_nullable=True)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK to patients table',
               existing_nullable=False)
    op.alter_column('visits', 'visit_number',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Unique visit ID: VIS-YYYY-NNNNN',
               existing_nullable=False)
    op.drop_index(op.f('ix_system_settings_is_deleted'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.alter_column('system_settings', 'category',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Category for grouping (features, display, limits)',
               existing_nullable=True)
    op.alter_column('system_settings', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Human-readable description',
               existing_nullable=True)
    op.alter_column('system_settings', 'value',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Setting value',
               existing_nullable=False)
    op.alter_column('system_settings', 'key',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Setting key (unique identifier)',
               existing_nullable=False)
    op.create_index('idx_icd10_usage', 'icd10_codes', ['usage_count'], unique=False)
    op.create_index('idx_icd10_search', 'icd10_codes', ['search_text'], unique=False, postgresql_using='gin')
    op.create_index('idx_icd10_common', 'icd10_codes', ['common_in_india'], unique=False)
    op.create_index('idx_icd10_category', 'icd10_codes', ['category'], unique=False)
    op.drop_index(op.f('ix_diagnoses_is_deleted'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_id'), table_name='diagnoses')
    op.create_index('idx_diagnoses_visit', 'diagnoses', ['visit_id'], unique=False)
    op.create_index('idx_diagnoses_type', 'diagnoses', ['diagnosis_type'], unique=False)
    op.create_index('idx_diagnoses_patient', 'diagnoses', ['patient_id'], unique=False)
    op.create_index('idx_diagnoses_icd10', 'diagnoses', ['icd10_code'], unique=False)
    op.create_index('idx_diagnoses_date', 'diagnoses', ['diagnosed_date'], unique=False)
    op.alter_column('diagnoses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('diagnoses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('diagnoses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('visit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('note_type', sa.VARCHAR(length=20), server_default=sa.text("'soap'::character varying"), autoincrement=False, nullable=False),
    sa.Column('subjective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('template_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('locked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('locked_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='clinical_notes_created_by_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], name='clinical_notes_locked_by_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='clinical_notes_patient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], name='clinical_notes_visit_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='clinical_notes_pkey')
    )
    op.create_index('idx_clinical_notes_visit_primary', 'clinical_notes', ['visit_id', 'is_primary'], unique=False)
    op.create_index('idx_clinical_notes_visit_id', 'clinical_notes', ['visit_id'], unique=False)
    op.create_index('idx_clinical_notes_patient_id', 'clinical_notes', ['patient_id'], unique=False)
    op.create_index('idx_clinical_notes_is_deleted', 'clinical_notes', ['is_deleted'], unique=False)
    op.create_index('idx_clinical_notes_created_by', 'clinical_notes', ['created_by'], unique=False)
    op.create_index('idx_clinical_notes_created_at', 'clinical_notes', ['created_at'], unique=False)
    op.create_table('note_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('note_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('specialty', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('subjective_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objective_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assessment_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('plan_template', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='note_templates_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='note_templates_pkey')
    )
    op.create_index('idx_note_templates_note_type', 'note_templates', ['note_type'], unique=False)
    op.create_index('idx_note_templates_is_active', 'note_templates', ['is_active'], unique=False)
    # ### end Alembic commands ###
