"""
Visit Schemas
=============

Purpose:
    Pydantic schemas for Visit model validation and serialization.
    Handles request/response data transformation.

Module: app/schemas/visit.py
Phase: 2A (Visit Models)

References:
    - Phase 2A Spec: docs/phases/phase2/Phase2A_VisitModels.md
    - Visit Model: app/models/visit.py

Schema Types:
    - VisitBase: Common fields for all visit schemas
    - VisitCreate: Input for creating a visit
    - VisitUpdate: Input for updating a visit
    - VisitStatusUpdate: Input for status-only updates
    - VisitResponse: Output with computed fields
    - VisitListResponse: Paginated list response
    - VisitSummary: Minimal info for lists/dropdowns

Used By:
    - app/api/v1/visits/router.py (API endpoints)
    - app/services/visit_service.py (Business logic)
"""

from pydantic import BaseModel, Field, ConfigDict, computed_field
from typing import Optional, List
from datetime import date, datetime
from uuid import UUID

from app.models.enums import VisitStatus, VisitType, Priority


# =============================================================================
# BASE SCHEMAS
# =============================================================================

class VisitBase(BaseModel):
    """Base schema with common visit fields."""
    
    patient_id: UUID = Field(..., description="Patient UUID")
    assigned_doctor_id: Optional[UUID] = Field(None, description="Assigned doctor UUID")
    visit_date: date = Field(default_factory=date.today, description="Date of visit")
    visit_type: VisitType = Field(default=VisitType.CONSULTATION, description="Type of visit")
    priority: Priority = Field(default=Priority.NORMAL, description="Queue priority")
    department: Optional[str] = Field(None, max_length=100, description="Department name")
    chief_complaint: Optional[str] = Field(None, description="Main reason for visit")
    notes: Optional[str] = Field(None, description="Additional notes")


# =============================================================================
# INPUT SCHEMAS (Create/Update)
# =============================================================================

class VisitCreate(VisitBase):
    """
    Schema for creating a new visit.
    
    Required fields:
        - patient_id: Must reference existing patient
        
    Auto-generated:
        - visit_number: Generated by VisitNumberGenerator
        - status: Defaults to REGISTERED
        - check_in_time: Set on creation
    """
    pass


class VisitUpdate(BaseModel):
    """
    Schema for updating an existing visit.
    
    All fields are optional - only provided fields are updated.
    Status should be updated via VisitStatusUpdate for validation.
    """
    
    assigned_doctor_id: Optional[UUID] = None
    visit_date: Optional[date] = None
    visit_type: Optional[VisitType] = None
    priority: Optional[Priority] = None
    department: Optional[str] = Field(None, max_length=100)
    chief_complaint: Optional[str] = None
    notes: Optional[str] = None


class VisitStatusUpdate(BaseModel):
    """
    Schema for updating visit status only.
    
    Status transitions are validated in the service layer.
    Cancellation reason is required when status is CANCELLED.
    """
    
    status: VisitStatus = Field(..., description="New status")
    cancellation_reason: Optional[str] = Field(
        None, 
        description="Required when status is CANCELLED"
    )
    
    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "status": "waiting"
                },
                {
                    "status": "cancelled",
                    "cancellation_reason": "Patient did not show up"
                }
            ]
        }
    )


# =============================================================================
# OUTPUT SCHEMAS (Response)
# =============================================================================

class PatientSummary(BaseModel):
    """Minimal patient info for visit responses."""
    
    id: UUID
    mrn: str
    full_name: str
    phone: str
    gender: str
    date_of_birth: Optional[date] = None
    blood_group: Optional[str] = None
    email: Optional[str] = None
    
    model_config = ConfigDict(from_attributes=True)


class DoctorSummary(BaseModel):
    """Minimal doctor info for visit responses."""
    
    id: UUID
    full_name: str
    
    model_config = ConfigDict(from_attributes=True)


class VisitResponse(BaseModel):
    """
    Full visit response with all fields and computed properties.
    
    Includes:
        - All visit fields
        - Patient summary (name, MRN, phone)
        - Doctor summary (name)
        - Computed wait time and duration
    """
    
    id: UUID
    visit_number: str
    patient_id: UUID
    assigned_doctor_id: Optional[UUID]
    visit_date: date
    visit_type: VisitType
    status: VisitStatus
    priority: Priority
    department: Optional[str]
    chief_complaint: Optional[str]
    check_in_time: Optional[datetime]
    consultation_start_time: Optional[datetime]
    consultation_end_time: Optional[datetime]
    cancellation_reason: Optional[str]
    notes: Optional[str]
    is_deleted: bool
    created_at: datetime
    updated_at: datetime
    
    # Nested objects
    patient: Optional[PatientSummary] = None
    assigned_doctor: Optional[DoctorSummary] = None
    
    model_config = ConfigDict(from_attributes=True)
    
    @computed_field
    @property
    def patient_name(self) -> Optional[str]:
        """Patient full name for convenience."""
        return self.patient.full_name if self.patient else None
    
    @computed_field
    @property
    def doctor_name(self) -> Optional[str]:
        """Doctor full name for convenience."""
        return self.assigned_doctor.full_name if self.assigned_doctor else None
    
    @computed_field
    @property
    def wait_time_minutes(self) -> Optional[int]:
        """
        Minutes waiting since check-in.
        Only calculated for WAITING status.
        """
        if self.status != VisitStatus.WAITING or not self.check_in_time:
            return None
        
        now = datetime.utcnow()
        delta = now - self.check_in_time.replace(tzinfo=None)
        return int(delta.total_seconds() / 60)
    
    @computed_field
    @property
    def consultation_duration_minutes(self) -> Optional[int]:
        """
        Duration of consultation in minutes.
        Only calculated when consultation has ended.
        """
        if not self.consultation_start_time or not self.consultation_end_time:
            return None
        
        delta = self.consultation_end_time - self.consultation_start_time
        return int(delta.total_seconds() / 60)


class VisitSummary(BaseModel):
    """
    Minimal visit info for lists and quick views.
    
    Used in:
        - Visit list tables
        - Patient visit history
        - Dashboard widgets
    """
    
    id: UUID
    visit_number: str
    patient_id: UUID
    patient_name: Optional[str] = None
    doctor_name: Optional[str] = None
    visit_date: date
    visit_type: VisitType
    status: VisitStatus
    priority: Priority
    chief_complaint: Optional[str]
    check_in_time: Optional[datetime]
    
    model_config = ConfigDict(from_attributes=True)


# =============================================================================
# LIST/PAGINATION SCHEMAS
# =============================================================================

class VisitListResponse(BaseModel):
    """Paginated list of visits."""
    
    items: List[VisitSummary]
    total: int
    page: int
    size: int
    pages: int


class VisitStatsResponse(BaseModel):
    """Visit statistics response."""
    
    total: int
    by_status: dict[str, int]
    by_type: dict[str, int]
    average_wait_time_minutes: Optional[float]
    average_consultation_minutes: Optional[float]
